#!/bin/bash
#PBS -m abe
#PBS -V
#PBS -l nodes=grad06:ppn=16:cluster-Grad,walltime=05:00:00
#PBS -M guilherme.carvalho@edu.pucrs.br
#PBS -r n
#PBS -j oe
#PBS -d /home/pp12709/openmp/t1/pp_t1/
#############
echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo `cat $PBS_NODEFILE | uniq`
echo
echo JOB_ID:
echo `echo $PBS_JOBID`
echo ################

export OMP_NUM_THREADS=2
./sum-par 1> saida_par_01_2t.txt 2> tempos_par_01_2t.txt
echo ""

export OMP_NUM_THREADS=4
./sum-par 1> saida_par_01_4t.txt 2> tempos_par_01_4t.txt
echo ""

export OMP_NUM_THREADS=8
./sum-par 1> saida_par_01_8t.txt 2> tempos_par_01_8t.txt
echo ""

export OMP_NUM_THREADS=16
./sum-par 1> saida_par_01_16t.txt 2> tempos_par_01_16t.txt
echo ""

############# If running a sequential or openMP program

################
echo Final Time is `date`
