#!/bin/bash
#PBS -m abe
#PBS -V
#PBS -l nodes=grad06:ppn=1:cluster-Grad,walltime=00:01:00
#PBS -M guilherme.carvalho@edu.pucrs.br
#PBS -r n
#PBS -j oe
#PBS -d /home/pp12709/openmp/t1
#############
echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo `cat $PBS_NODEFILE | uniq`
echo
echo JOB_ID:
echo `echo $PBS_JOBID`
echo ################

./sum_seq 1> saida_seq_01.txt 2> tempos_seq_01.txt
echo ""


############# If running a sequential or openMP program

################
echo Final Time is `date`